plugins {
    id 'java'
}

group = 'ru.axothy'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // Kafka Client
    implementation 'org.apache.kafka:kafka-clients:3.5.1'

    // MongoDB Driver
    implementation 'org.mongodb:mongodb-driver-sync:4.10.2'

}

jar {
    manifest {
        attributes(
                'Main-Class': 'ru.axothy.KafkaToMongoApp'
        )
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}
