apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-company-application-dc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airline-company-application
  template:
    metadata:
      labels:
        app: airline-company-application
    spec:
      containers:
        - name: airline-company-application
          image: docker.io/axothy/airline-company-application:latest
          ports:
            - containerPort: 8080