apiVersion: v1
kind: Service
metadata:
  name: airline-company-application-svc
spec:
  selector:
    app: airline-company-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP